name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and test
      run: |
        yarn
        yarn test
      env:
        CI: true
